### PR TITLE
Added support for versioning vendor utilities 

### PR DESCRIPTION
**Pull request by cgotcu**

### CODE REVIEW

**Comment by wickett** [comment]
This looks great!

**Comment by cgotcu** [comment]
Thanks!
This should allow you to close issues #90 and #91. I'm going to do another pull request on a separate branch (as suggested by @apolloclark ) for integration with owasp zap once a new zap gem is published with a small but necessary change.

**Comment by wickett** [comment]
Merging!

Side idea.  One of the things we might try is adding attack aliases as plain text files.  That way you can BYOAA (Bring Your Own Attack Aliases).  This could look something like this:

attack-alias.yml
```
arachni-xss:
    cmd: arachni --check=xss* <url>
    desc: This is something great
    requires: <url>
foo:
    cmd: arachni --check=foo* <url>
    desc: This is something greater
    requires: <url>
...
```

The idea is allow the user to bring a definition of all the attack aliases right along side their `.attack` files.  Just an idea, but wanted to see if you or @apolloclark think that is worthwhile.

**Comment by apolloclark** [comment]
Awesome, thanks @cgotcu :)

**Pull request merged**
