### PR TITLE
Added option to pipe report-specific output to file

### PR DESCRIPTION
**Pull request by cgotcu**

### CODE REVIEW

**Comment by cgotcu** [comment]
We could also upgrade arachni to 1.1 and nokogiri to 1.6.5 but that means we have to drop 1.9 support. There's no direct reason for upgrading those two other than they are pretty old. Is there any value to maintaining 1.9 support?

**Comment by apolloclark** [comment]
I'm fine with the upgrades and dropping ruby 1.9. What do you think @wickett ?

**Comment by karthequian** [comment]
I don't think so @cgotcu! @wickett ping on this.

**Comment by wickett** [comment]
This looks great.  This fell off my radar and I am sorry for not merging this until now.  Thanks @cgotcu

**Comment by wickett** [comment]
hmm, that just broke that travis build

**Comment by wickett** [comment]
I will have to take a look later tonight at it

**Pull request merged**
