### PR TITLE
Curl cookies

### PR DESCRIPTION
**Pull request by blischalk**
Parse curl Set-Cookie header to enable verification of cookie attributes. This should address issue #101

### CODE REVIEW

**Comment by wickett** [comment]
Looks good to me. Do we need to change any tests?

**Comment by karthequian** [comment]
lgtm

**Comment by blischalk** [comment]
I don't believe any tests need to change. Running `rake test` and `cucumber` both appear to be green.

**Comment by wickett** [comment]
@blischalk yeah was just thinking if we need to update any of the curl-based tests

**Pull request merged**
